### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by fulldecent** [azu/github-sponsor-report#1]
Could you please show the output of this program?

Does it make a GitHub Pages repo that hosts data and an image?

If so, can you please link to a deployed example?

**Comment by azu** [comment]
I've added a screenshot as an example.
https://github.com/azu/github-sponsor-report/blob/main/README.md#screenshot

https://github.com/azu/github-sponsor-report-template show blank data by default.
It is expected because the repository will includes own private sponsors data.
(I do not have dummy account that is sponsored by someone for actual example)

**Comment by fulldecent** [comment]
Very cool, thank you!
